apiVersion: v1
kind: Service
metadata:
  name: vpromq01
  namespace: default
spec:
  selector:
    app: vpromq01
  type: ClusterIP
  ports:
  - port: 15672
    protocol: TCP
    targetPort: vpromq01-port
