apiVersion: v1
kind: Service
metadata:
  name: vprosearch01
  namespace: default
spec:
  selector:
    app: vpromc
  type: ClusterIP
  ports:
  - port: 11211
    protocol: TCP
    targetPort: promc-port
