apiVersion: v1
kind: Service
metadata:
  name: vprofileapp-service
  namespace: default
spec:
  selector:
    app: vprofileapp
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: vproapp-port
