apiVersion: v1
kind: Service
metadata:
  name: vprofileapp
  namespace: default
spec:
  selector:
    app: vprofileapp
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: vprofileapp-port
